[core]
workspace_base = "/home/nvidia/Projects/cybergym/eval_qwen3_5_122b_a10b/tmp/arvo_8933-8f9c954d81cf4ac48710f69ef4adadda/workspace"
cache_dir = "/home/nvidia/Projects/cybergym/eval_qwen3_5_122b_a10b/logs/arvo_8933-8f9c954d81cf4ac48710f69ef4adadda/cache"
file_store_path = "/home/nvidia/Projects/cybergym/eval_qwen3_5_122b_a10b/logs/arvo_8933-8f9c954d81cf4ac48710f69ef4adadda/file"
save_trajectory_path = "/home/nvidia/Projects/cybergym/eval_qwen3_5_122b_a10b/logs/arvo_8933-8f9c954d81cf4ac48710f69ef4adadda/trajectory"
run_as_openhands = false

[llm]
model = "openai/Qwen/Qwen3.5-122B-A10B"
max_output_tokens = 24576
top_p = 1.0
temperature = 0.0
base_url = "http://localhost:8000/v1"
input_cost_per_token = 0.0
output_cost_per_token = 0.0

[sandbox]
runtime_container_image = "docker.all-hands.dev/all-hands-ai/runtime:0.33-nikolaik"
runtime_binding_address = "127.0.0.1"

[sandbox.docker_runtime_kwargs]
auto_remove = true
